export const SITE_CONFIG = {
  name: "TEI-HA Construction Services Ltd",
  shortName: "TEI-HA",
  tagline: "Quality Is Our Priority",
  description:
    "AI-powered architecture and construction company based in Uganda, serving clients worldwide. Specializing in architectural design, civil engineering, construction, interior design, and project management with AI-enhanced workflows.",
  url: "https://teihaconstructionservices.com",
  ogImage: "https://teihaconstructionservices.com/opengraph-image.png",
  logo: "/tei ha pics/logo.png",
  sameAs: [
    "https://www.youtube.com/@Tei-haConstructionServices",
    "https://twitter.com/teiha_construction",
    "https://github.com/artsrock099-alt/teiha-construction",
  ],
  links: {
    twitter: "https://twitter.com/teiha_construction",
    github: "https://github.com/artsrock099-alt/teiha-construction",
    youtube: "https://www.youtube.com/@Tei-haConstructionServices",
    whatsapp: "https://wa.me/256200911184",
  },
  business: {
    telephone: "+256200911184",
    whatsapp: "+256200911184",
    email: "teihaconstructionservices@gmail.com",
    address: {
      streetAddress: "Nansana Municipality along Hoima Rd, DT Complex",
      addressLocality: "Nansana",
      addressRegion: "Wakiso",
      postalCode: "115420",
      addressCountry: "UG",
    },
    geo: {
      latitude: 0.3476,
      longitude: 32.5825,
    },
    tin: "1047520346",
    foundingDate: "2020",
    openingHours: [
      { day: "Monday", opens: "08:00", closes: "17:00" },
      { day: "Tuesday", opens: "08:00", closes: "17:00" },
      { day: "Wednesday", opens: "08:00", closes: "17:00" },
      { day: "Thursday", opens: "08:00", closes: "17:00" },
      { day: "Friday", opens: "08:00", closes: "17:00" },
      { day: "Saturday", opens: "09:00", closes: "13:00" },
    ],
    areaServed: [
      "Uganda",
      "East Africa",
      "Kampala",
      "Wakiso",
      "Nansana",
      "Mukono",
      "Entebbe",
      "Jinja",
    ],
    servicesOffered: [
      "Architectural Design",
      "Civil & Structural Engineering",
      "Construction Services",
      "Project Planning & Project Management",
      "Highway Engineering",
      "Geotechnical Engineering",
      "Surveying",
      "Electrical & Mechanical Engineering",
      "Water Supply & Sanitation Engineering",
      "Environmental Engineering",
      "Interior Design & Finishing",
      "Renovation & Remodeling",
      "Construction Supervision & Quality Assurance",
      "Smart Building Consulting",
      "Sustainable Design",
      "General Material Supply",
    ],
  },
};

export const NAV_LINKS = [
  { name: "Home", href: "/" },
  { name: "AI Studio", href: "/ai-studio" },
  { name: "Blog", href: "/blog" },
  { name: "Resources", href: "/resources" },
  { name: "Projects", href: "/projects" },
  { name: "Services", href: "/services" },
  { name: "Investors", href: "/investors" },
  { name: "Contact", href: "/contact" },
];

export const FOOTER_LINKS = {
  company: [
    { name: "About Us", href: "/about" },
    { name: "Careers", href: "/careers" },
    { name: "Press", href: "/press" },
  ],
  services: [
    { name: "Architecture", href: "/services/architecture" },
    { name: "Civil & Structural Engineering", href: "/services/civil-engineering" },
    { name: "Construction", href: "/services/construction" },
    { name: "Project Management", href: "/services/project-management" },
    { name: "Highway Engineering", href: "/services/highway-engineering" },
    { name: "Interior Design", href: "/services/interior-design" },
  ],
  resources: [
    { name: "Blog", href: "/blog" },
    { name: "Guides", href: "/resources/guides" },
    { name: "Case Studies", href: "/resources/case-studies" },
  ],
  legal: [
    { name: "Privacy Policy", href: "/privacy" },
    { name: "Terms of Service", href: "/terms" },
  ],
};
