export interface Project {
  id: string;
  slug: string;
  title: string;
  category: string;
  location: string;
  client: string;
  status: string;
  year: number;
  description: string;
  heroImage: string;
  gallery: string[];
  servicesUsed: string[];
  industry: string;
  projectSize: string;
  duration: string;
  designChallenges: string;
  designSolution: string;
  aiContribution: {
    title: string;
    description: string;
  }[];
  technologies: string[];
  sustainabilityHighlights: {
    title: string;
    value: string;
  }[];
  projectStats: {
    label: string;
    value: number;
    suffix?: string;
  }[];
  testimonial: {
    quote: string;
    author: string;
    role: string;
  };
  relatedProjects: string[];
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
}

export const PROJECTS: Project[] = [
  // Residential
  {
    id: "r1",
    slug: "residential-project-1",
    title: "Residential Project 1",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2024,
    description: "Elegant residential development with modern design and sustainable features.",
    heroImage: "/tei ha pics/residentail6.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "2,000 m²",
    duration: "12 months",
    designChallenges: "Optimizing space for family living while maintaining aesthetic appeal.",
    designSolution: "Open floor plan with natural light and smart storage solutions.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r2",
    slug: "residential-project-2",
    title: "Residential Project 2",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2023,
    description: "Modern residential complex with premium amenities.",
    heroImage: "/tei ha pics/residential.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "3,500 m²",
    duration: "18 months",
    designChallenges: "Creating a harmonious design within a tight urban lot.",
    designSolution: "Vertical design with rooftop gardens and communal spaces.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r3",
    slug: "residential-project-3",
    title: "Residential Project 3",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2023,
    description: "Luxury residential project with contemporary finishes.",
    heroImage: "/tei ha pics/residential1.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "2,800 m²",
    duration: "15 months",
    designChallenges: "Balancing luxury with functional living spaces.",
    designSolution: "High-end materials combined with practical design elements.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r4",
    slug: "residential-project-4",
    title: "Residential Project 4",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2022,
    description: "Stylish residential development with modern architecture.",
    heroImage: "/tei ha pics/residential3.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "4,200 m²",
    duration: "20 months",
    designChallenges: "Integrating green spaces into the urban environment.",
    designSolution: "Courtyard gardens and vertical greenery.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r5",
    slug: "residential-project-5",
    title: "Residential Project 5",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2022,
    description: "Premium residential project with top-notch facilities.",
    heroImage: "/tei ha pics/residential11.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "3,000 m²",
    duration: "16 months",
    designChallenges: "Ensuring privacy while fostering community.",
    designSolution: "Clustered units with shared amenities.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r6",
    slug: "residential-project-6",
    title: "Residential Project 6",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2021,
    description: "Elegant residential development with timeless design.",
    heroImage: "/tei ha pics/residential9.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "2,500 m²",
    duration: "14 months",
    designChallenges: "Creating a design that ages gracefully.",
    designSolution: "Classic architectural elements with modern amenities.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "r7",
    slug: "residential-project-7",
    title: "Residential Project 7",
    category: "Residential",
    location: "Kampala, Uganda",
    client: "Private Client",
    status: "Completed",
    year: 2021,
    description: "Modern residential project with smart home features.",
    heroImage: "/tei ha pics/residential5.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Construction"],
    industry: "Residential",
    projectSize: "3,800 m²",
    duration: "18 months",
    designChallenges: "Integrating smart technology seamlessly.",
    designSolution: "Pre-wired infrastructure and user-friendly interfaces.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },

  // Hospitality
  {
    id: "h1",
    slug: "hospitality-project-1",
    title: "Hospitality Project 1",
    category: "Hospitality",
    location: "Kampala, Uganda",
    client: "Hospitality Group",
    status: "Completed",
    year: 2024,
    description: "Luxury hotel with world-class amenities.",
    heroImage: "/tei ha pics/hospitality-1.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Interior Design", "Construction"],
    industry: "Hospitality",
    projectSize: "8,000 m²",
    duration: "24 months",
    designChallenges: "Creating a memorable guest experience.",
    designSolution: "Thoughtful space planning and premium finishes.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "h2",
    slug: "hospitality-project-2",
    title: "Hospitality Project 2",
    category: "Hospitality",
    location: "Kampala, Uganda",
    client: "Hospitality Group",
    status: "Completed",
    year: 2023,
    description: "Boutique hotel with unique design elements.",
    heroImage: "/tei ha pics/hospitality2.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Interior Design", "Construction"],
    industry: "Hospitality",
    projectSize: "4,500 m²",
    duration: "18 months",
    designChallenges: "Standing out in a competitive market.",
    designSolution: "Distinctive architectural style and personalized service spaces.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },


  // Industrial
  {
    id: "i1",
    slug: "industrial-project-1",
    title: "Industrial Project 1",
    category: "Industrial",
    location: "Kampala, Uganda",
    client: "Industrial Corporation",
    status: "Completed",
    year: 2024,
    description: "Modern industrial facility with efficient layout.",
    heroImage: "/tei ha pics/industrial.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Civil Engineering", "Construction"],
    industry: "Industrial",
    projectSize: "15,000 m²",
    duration: "24 months",
    designChallenges: "Optimizing workflow and logistics.",
    designSolution: "Functional layout with clear circulation paths.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "i2",
    slug: "industrial-project-2",
    title: "Industrial Project 2",
    category: "Industrial",
    location: "Kampala, Uganda",
    client: "Industrial Corporation",
    status: "Completed",
    year: 2023,
    description: "Warehouse and distribution center.",
    heroImage: "/tei ha pics/industrial2.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Civil Engineering", "Construction"],
    industry: "Industrial",
    projectSize: "20,000 m²",
    duration: "18 months",
    designChallenges: "Large-scale storage and efficient loading.",
    designSolution: "High-ceiling design with multiple loading bays.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "i3",
    slug: "industrial-project-3",
    title: "Industrial Project 3",
    category: "Industrial",
    location: "Kampala, Uganda",
    client: "Industrial Corporation",
    status: "Completed",
    year: 2023,
    description: "Manufacturing plant with specialized equipment.",
    heroImage: "/tei ha pics/industrial3.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Civil Engineering", "Construction"],
    industry: "Industrial",
    projectSize: "18,000 m²",
    duration: "22 months",
    designChallenges: "Accommodating heavy machinery and specific operational needs.",
    designSolution: "Reinforced structure and customized floor plans.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "i4",
    slug: "industrial-project-4",
    title: "Industrial Project 4",
    category: "Industrial",
    location: "Kampala, Uganda",
    client: "Industrial Corporation",
    status: "Completed",
    year: 2022,
    description: "Logistics hub with state-of-the-art facilities.",
    heroImage: "/tei ha pics/industrial4.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Civil Engineering", "Construction"],
    industry: "Industrial",
    projectSize: "25,000 m²",
    duration: "28 months",
    designChallenges: "Handling high-volume logistics operations.",
    designSolution: "Advanced material handling systems and efficient layout.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "i5",
    slug: "industrial-project-5",
    title: "Industrial Project 5",
    category: "Industrial",
    location: "Kampala, Uganda",
    client: "Industrial Corporation",
    status: "Completed",
    year: 2021,
    description: "Industrial complex with multiple units.",
    heroImage: "/tei ha pics/industrial12.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Civil Engineering", "Construction"],
    industry: "Industrial",
    projectSize: "30,000 m²",
    duration: "32 months",
    designChallenges: "Flexible space for diverse industrial uses.",
    designSolution: "Modular design that can be adapted to different needs.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },

  // Commercial
  {
    id: "c1",
    slug: "commercial-project-1",
    title: "Commercial Project 1",
    category: "Commercial",
    location: "Kampala, Uganda",
    client: "Commercial Development Group",
    status: "Completed",
    year: 2024,
    description: "Modern office building with contemporary design.",
    heroImage: "/tei ha pics/commercial1.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Interior Design", "Construction"],
    industry: "Commercial",
    projectSize: "10,000 m²",
    duration: "24 months",
    designChallenges: "Creating a professional yet inviting workspace.",
    designSolution: "Open floor plans with natural light and communal areas.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "c2",
    slug: "commercial-project-2",
    title: "Commercial Project 2",
    category: "Commercial",
    location: "Kampala, Uganda",
    client: "Commercial Development Group",
    status: "Completed",
    year: 2023,
    description: "Retail complex with multiple storefronts.",
    heroImage: "/tei ha pics/commercial2.jpeg",
    gallery: [],
    servicesUsed: ["Architecture", "Interior Design", "Construction"],
    industry: "Commercial",
    projectSize: "8,000 m²",
    duration: "18 months",
    designChallenges: "Maximizing retail space and foot traffic.",
    designSolution: "Strategic layout with anchor stores and pedestrian-friendly design.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },


  // Master Planning
  {
    id: "mp1",
    slug: "master-plan-1",
    title: "Master Plan 1",
    category: "Master Planning",
    location: "Kampala, Uganda",
    client: "Urban Development Authority",
    status: "Completed",
    year: 2024,
    description: "Comprehensive master plan for a new community.",
    heroImage: "/tei ha pics/plan.jpeg",
    gallery: [],
    servicesUsed: ["Urban Planning", "Architecture", "Civil Engineering"],
    industry: "Master Planning",
    projectSize: "50 hectares",
    duration: "24 months",
    designChallenges: "Creating a sustainable and inclusive community.",
    designSolution: "Mixed-use zoning with green spaces and essential amenities.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "mp2",
    slug: "master-plan-2",
    title: "Master Plan 2",
    category: "Master Planning",
    location: "Kampala, Uganda",
    client: "Urban Development Authority",
    status: "Completed",
    year: 2023,
    description: "Urban renewal master plan for a city district.",
    heroImage: "/tei ha pics/plan1.jpeg",
    gallery: [],
    servicesUsed: ["Urban Planning", "Architecture", "Civil Engineering"],
    industry: "Master Planning",
    projectSize: "30 hectares",
    duration: "18 months",
    designChallenges: "Preserving heritage while modernizing.",
    designSolution: "Adaptive reuse of existing structures with new developments.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "mp3",
    slug: "master-plan-3",
    title: "Master Plan 3",
    category: "Master Planning",
    location: "Kampala, Uganda",
    client: "Urban Development Authority",
    status: "Completed",
    year: 2022,
    description: "Master plan for a new industrial park.",
    heroImage: "/tei ha pics/plan2.jpeg",
    gallery: [],
    servicesUsed: ["Urban Planning", "Architecture", "Civil Engineering"],
    industry: "Master Planning",
    projectSize: "80 hectares",
    duration: "28 months",
    designChallenges: "Optimizing infrastructure and logistics.",
    designSolution: "Strategic zoning with efficient transportation links.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "mp4",
    slug: "master-plan-4",
    title: "Master Plan 4",
    category: "Master Planning",
    location: "Kampala, Uganda",
    client: "Urban Development Authority",
    status: "Completed",
    year: 2021,
    description: "Master plan for a residential community.",
    heroImage: "/tei ha pics/plan3.jpeg",
    gallery: [],
    servicesUsed: ["Urban Planning", "Architecture", "Civil Engineering"],
    industry: "Master Planning",
    projectSize: "40 hectares",
    duration: "22 months",
    designChallenges: "Creating a family-friendly environment.",
    designSolution: "Parks, schools, and community centers integrated into the plan.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  },
  {
    id: "mp5",
    slug: "master-plan-5",
    title: "Master Plan 5",
    category: "Master Planning",
    location: "Kampala, Uganda",
    client: "Urban Development Authority",
    status: "Completed",
    year: 2020,
    description: "Comprehensive master plan for a mixed-use development.",
    heroImage: "/tei ha pics/plan5.jpeg",
    gallery: [],
    servicesUsed: ["Urban Planning", "Architecture", "Civil Engineering"],
    industry: "Master Planning",
    projectSize: "60 hectares",
    duration: "30 months",
    designChallenges: "Balancing commercial, residential, and recreational spaces.",
    designSolution: "Integrated design with walkable streets and public spaces.",
    aiContribution: [],
    technologies: [],
    sustainabilityHighlights: [],
    projectStats: [],
    testimonial: { quote: "", author: "", role: "" },
    relatedProjects: [],
    seo: { title: "", description: "", keywords: [] }
  }
];

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((project) => project.slug === slug);
}

export const PROJECT_CATEGORIES = ["All", "Residential", "Hospitality", "Industrial", "Commercial", "Master Planning"];

